# Site Settings
title: Sofian Bll
description: Développeur créatif & Motion Designer
url: "https://sofian-bll.github.io"
baseurl: "/My-Portolio"

# Contact
email: sofianebelloul@gmail.com
github_username: Sofian-bll
linkedin_username: Sofianbll

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md